### PR TITLE
Switch for gitlab images, and Gihub workflow skip-linter label

### LINKED ISSUE #52: Skip superlinter
## What is the issue?
From time to time we experience bugs with the Github Superlinter and it could fail. Proposing that we implement a `skip-linter` label to skip the linter-test.

## Suggestion(s)/solution(s) [Optional]
Something like this should do the job: 
```yml
jobs:
  linter:
    runs-on: ubuntu-latest
    if: github.event.pull_request.labels.*.name != 'skip-linter'
    steps:
...

```

### :warning: Note
I tried to implement this, but the linter-job is set as `required` so it didn't work. I think it needs to be turned off by the repo owner to work, but I'm not sure. 

## Checklist (after created issue)
- [x] Added label(s)
- [ ] Added to project
- [ ] Added to milestone

### PR DESCRIPTION
**Pull request by claesgill**
## Closes/fixes/resolves issue(s)?
Closes #52 

## What was added/changed/fixed?
- Switch for gitlab images
- Gihub workflow skip-linter label

## Checklist (after created PR)
- [x] Added reviewers
- [x] Added assignee(s)
- [x] Added label(s)
- [x] Added to project
- [x] Added to milestone

### CODE REVIEW

**Review by fredrikhgrelland — CHANGES_REQUESTED** [review]
Why have separate switch? We could implement image variables with default values for docker hub. If needed, these can be changed to whatever image.-.

**Comment by zhenik** [comment]
> Why have separate switch? We could implement image variables with default values for docker hub. If needed, these can be changed to whatever image.-.

I agree.

We could also setup default values pointing to default for `sidecar_task.config.image` pointing to `meta.connect.sidecar_image` or `envoyproxy/envoy:v${NOMAD_envoy_version}` from [documentation](https://www.nomadproject.io/docs/job-specification/sidecar_task)

**Comment by claesgill** [comment]
> Why have separate switch? We could implement image variables with default values for docker hub. If needed, these can be changed to whatever image.-.

That's a fairly good point. However, I think the switch makes it easier to quickly debug/test locally.

Because our github workflow requires to pull images from Docker Hub we would need the default images to be linked to Docker. Without the switch we would need to type out the GitLab address (e.g. `gitlab-container-registry.service.v2.minerva.loc/datastack/terraform-nomad-postgres/postgres:12-alpine`) each time we work on a new branch..

If we can find a way of avoiding to type or copy/paste the custom image address, I agree that we can remove the switch.

**Comment by pdmthorsrud** [comment]
After looking at it I think variables with default might be more suitable. It's easier to read, and makes a lot of sense; you "supply" your own image, or else you use "our" (default) images

**Comment by claesgill** [comment]
@pdmthorsrud @dangernil @zhenik @fredrikhgrelland I don't think this is as relevant anymore. Do you agree that we close this PR?

**Pull request closed without merging**
