### PR TITLE
Release 0.2.0

### PR DESCRIPTION
**Pull request by claesgill**
## Closes/fixes/resolves issue(s)?
[Milestone 0.2.0](https://github.com/fredrikhgrelland/terraform-nomad-postgres/milestone/3) completed

## What was added/changed/fixed?
- Ready for release 0.2.0
- Removed broken links in READMEs

## Checklist (after created PR)
- [x] Added reviewers
- [x] Added assignee(s)
- [x] Added label(s)
- [x] Added to project
- [x] Added to milestone

### CODE REVIEW

**Review by zhenik — DISMISSED** [review]

**Comment by Neha-Sinha2305** [comment]
@claesgill : Need to remove links that point to the deleted template_eample folder. for example check the bad link in this readme.md :
https://github.com/fredrikhgrelland/terraform-nomad-postgres/tree/release_0.2.0/example

**Comment by Neha-Sinha2305** [comment]
That was just one of the places where we had the broken link, it will be nice if you search and remove in all places where we link to template_example folder.
Another one : https://github.com/fredrikhgrelland/terraform-nomad-postgres/tree/release_0.2.0/example/vagrant_box_example

**Comment by claesgill** [comment]
> That was just one of the places where we had the broken link, it will be nice if you search and remove in all places where we link to template_example folder.
> Another one : https://github.com/fredrikhgrelland/terraform-nomad-postgres/tree/release_0.2.0/example/vagrant_box_example

I think that should be done in a separate PR since the release should only contain the release change.

I guess I can close this PR and fix the links and create a new release afterwards. Or I can create a issue for this that should be included in the next release. What do you think?

**Comment by Neha-Sinha2305** [comment]
> > That was just one of the places where we had the broken link, it will be nice if you search and remove in all places where we link to template_example folder.
> > Another one : https://github.com/fredrikhgrelland/terraform-nomad-postgres/tree/release_0.2.0/example/vagrant_box_example
> 
> I think that should be done in a separate PR since the release should only contain the release change.
> 
> I guess I can close this PR and fix the links and create a new release afterwards. Or I can create a issue for this that should be included in the next release. What do you think?

Since, template_example was deleted in this release so this clean up task should have been done in the PR that was used to delete that folder.IMHO it's a small task and should be done before making the release...idea is to have cleaner complete release but you can choose to disagree :)

**Comment by pdmthorsrud** [comment]
> Since, template_example was deleted in this release so this clean up task should have been done in the PR that was used to delete that folder.IMHO it's a small task and should be done before making the release...idea is to have cleaner complete release but you can choose to disagree :)

I'm OK with removing the links inside this PR, I don't think that's a biggie. Definitely not something that should become the norm, but a one-off is a-ok :D

**Comment by claesgill** [comment]
> > > That was just one of the places where we had the broken link, it will be nice if you search and remove in all places where we link to template_example folder.
> > > Another one : https://github.com/fredrikhgrelland/terraform-nomad-postgres/tree/release_0.2.0/example/vagrant_box_example
> > 
> > 
> > I think that should be done in a separate PR since the release should only contain the release change.
> > I guess I can close this PR and fix the links and create a new release afterwards. Or I can create a issue for this that should be included in the next release. What do you think?
> 
> Since, template_example was deleted in this release so this clean up task should have been done in the PR that was used to delete that folder.IMHO it's a small task and should be done before making the release...idea is to have cleaner complete release but you can choose to disagree :)

That's a good point! I'll fix it in this PR then 😄 

EDIT: 
I realized middle way that there was a lot of broken links :sweat_smile: If I had know beforehand I would created a separate PR. However, it's done, but I think we might want to avoid doing this in a release PR in the future. As you said it should have been done in the remove-template_example-PR, so that's on me ofc :facepalm:

**Review by zhenik — APPROVED** [review]
LGTM. We probably need to use `http` links instead of `relative path` links in the original template, makes it easier when we need to sync module with template

**Review by dangernil — APPROVED** [review]
LGTM

**Pull request merged**
